const mysql = require('mysql2/promise');

const degreePrograms = {
  "Mechanical Engineering and Production Technology": [
    "3D Design", "Algebra", "Basics of Mechanical Drawing", "Basics of Programming",
    "Basics of Strength Theory", "Coatings", "Differential Calculus", "Dynamics",
    "Electrical Engineering", "Finnish 1", "Finnish 2", "Finnish 3", "Finnish 4",
    "Geometry and Linear Algebra", "Hydraulics", "Integral Calculus",
    "Introduction to Technical Physics", "Machine Elements 1", "Machine Elements 2",
    "Machining", "Manufacturing Methods", "Materials Engineering", "Sheet Metal Work",
    "Statics", "Strength Theory", "Strength Theory in Design", "Technical English 1",
    "Tolerances and Fits", "Welding Engineering"
  ],
  "Konetekniikka": [
    "3D-suunnittelu", "Algebra", "Differentiaalilaskenta", "Dynamiikka",
    "Geometria ja lineaarialgebra", "Hitsaustekniikka", "Hydraulikka",
    "Integraalilaskenta", "Koneenosat 1", "Koneenosat 2", "Koneensuunnittelun projekti",
    "Levytyöt", "Lujuusopin perusteet", "Lujuusoppi", "Lujuusoppi suunnittelussa",
    "Materiaalitekniikka", "Ohjelmoinnin perusteet", "Ohutlevytuotteen suunnittelu",
    "Pintakäsittelyt", "Sähkötekniikan perusteet", "Statiikka", "Tekniikan englanti 1",
    "Tekniikan ruotsi 1", "Tekniikan ruotsi 2", "Tekniikan viestintä 1",
    "Tekniikan viestintä 2", "Toleranssit ja sovitteet", "Valmistusmenetelmät"
  ],
  "Information and Communication Technology Robotics": [
    "Algebra", "Basics of Programming", "Collaborative Robotics",
    "Database Design and Programming", "Differential Calculus", "Finnish 1",
    "Finnish 2", "Finnish 3", "Finnish 4", "Geometry and Linear Algebra",
    "Integral Calculus", "Introduction to Information Networks",
    "Introduction to Robotics and Programming", "Introduction to Technical Physics",
    "Linux Management", "Object Oriented Programming", "Robot Kinematics",
    "Robot Programming and Factory Simulation", "Robotic Process Automation",
    "Software Application Development", "Technical English 1", "Machine Vision",
    "Introduction to Machine Learning", "Dynamics", "Entrepreneurship",
    "Control Systems", "Product Design"
  ],
  "Tieto- ja viestintätekniikan": [
    "Ohjelmoinnin perusteet", "ICT Diili", "Algebra", "Web-tekniikoiden perusteet",
    "Web-projekti", "Kuvankäsittely", "Geometria ja lineaarialgebra", "Olio-ohjelmointi",
    "Ohjelmistokehitys", "Mekaniikka", "Tekniikan englanti 1", "Linux-hallinta",
    "Tietoverkkojen perusteet", "Windows-järjestelmät", "Sähkö ja magnetismi",
    "Mobiiliohjelmointi", "Asiakaspuolen web-ohjelmointi", "Aaltoilike ja optiikka",
    "Tekniikan englanti 2", "Ohjaimet ja elektroniikka", "IoT, arkkitehtuurit",
    "Mittaustekniikan perusteet", "Differentiaallaskenta", "Integraallaskenta",
    "Web-ohjelmointi", "Tietokantojen suunnittelu ja ohjelmointi", "Tekniikan ruotsi 2",
    "Kytkinverkot", "Reititinverkot", "Verkon hallinta", "Tekniikan ruotsi 1"
  ],
  "Sustainable Urban Design": [
    "Finnish 1", "Introduction to Technical Physics", "Geometry and Linear Algebra",
    "Algebra", "Finnish 2", "Finnish 3", "Chemistry", "Finnish 4"
  ],
  "Computer Applications": [
    "Agile Business Solution Development", "Applied Application Project",
    "Basics of Data Analysis", "Basics of Programming", "Building a Static Website",
    "Cloud Services", "Cloud-Based Business Solutions", "Computer Networks and Security",
    "Content Management Systems", "Data Processing with Python", "Databases",
    "Design Factory Project", "Digital and Social Media Analytics",
    "English Communication in Customer Projects", "Finish 1", "Finish 2", "Finish 3",
    "Finish 4", "Foundations of Data Engineering", "JavaScript", "Minthesis",
    "Object-Oriented Programming", "Operating Systems", "Predictive Analytics with Python",
    "Software Design", "Software Development Tools", "Software Robotics and Automation",
    "Software Testing", "Web Accessibility", "Web Framework Project", "Web Programming",
    "Web Services"
  ],
  "Electrical and Automation Engineering": [
    "Orientation to Engineering Studies", "Geometry and Linear Algebra",
    "Basics of Automation Technology", "Sustainable Development.Now", "Finnish 1",
    "Algebra", "Technical English 1", "Finnish 2", "Electrical Measurements",
    "Electrical and Automation Laboratories", "Differential Calculus", "Finnish 3",
    "Theoretical Electrical Engineering - DC", "Electricity Distribution Networks",
    "Basics of Programming", "Integral Calculus", "Finnish 4", "Measuring Systems",
    "Mechanics", "3D Modelling", "Logic Programming and User Interfaces",
    "Data Networks and Data Security", "Fluids, Heat and Thermodynamics", "Data Analysis",
    "IoT Systems", "Electricity, Magnetism and Waves", "Theoretical Electrical Engineering - AC",
    "Energy Systems of Buildings", "Electric Drives in Buildings",
    "Automation of Electrical Networks in Buildings", "Small-scale Production and Storage of Electricity",
    "Developing Professional Identity", "Working on an International Project",
    "Differential Equations and Probability Calculus", "Process Measurements",
    "Technical English 2", "Industrial Internet of Things"
  ],
  "Construction Engineering": [
    "Orientation to Construction Studies", "Basics of Construction Industry",
    "Introduction to Technical Physics", "Geometry and Linear Algebra", "Finnish 1",
    "Construction Materials", "Timber Construction", "Basics of Technical Drawings",
    "Building Chemistry", "Algebra", "Finnish 2", "Basics of Building Information Modelling (BIM)",
    "Basics of Geotechnics", "Sustainable Development.Now", "Differential Calculus",
    "Statics 1", "Finnish 3", "Sustainability and Housing Health", "Basics of Building Physics",
    "Energy Efficiency and Renewable Energy", "Statics 2", "Integral Calculus", "Finnish 4",
    "Conceptual Design of the Structures", "Basics of Concrete Construction",
    "Foundation Engineering", "Surveying Techniques in Construction Site",
    "Strength of Materials 1", "Technical English 1", "Load-Bearing Frames of Buildings",
    "Basics of Project Management", "Strength of Materials 2", "Concrete Technology",
    "Basics of Concrete Structures", "Technical English 2", "Concrete Structure Design",
    "Building Services Systems (HVAC)", "Durability of Materials",
    "Construction Management and Economics", "Construction Site Safety", "Structural Analysis",
    "Advanced Building Physics", "Basic of Building Information Modeling", "Concrete Construction",
    "Advanced Concrete Structures Design", "Design of Steel Structures",
    "Industrial and Commercial Buildings", "Steel Construction", "Advanced Mechanics"
  ],
  "Alykkään ja kestävän muotoilun": [
    "Design of Steel Structures", "Industrial and Commercial Buildings", "Steel Construction",
    "Advanced Mechanics", "Luomostelu ja visualisointi", "Digitaaliset oppimisympäristöt",
    "Muotoilu kulttuurissa", "Muotoilustudio", "Kestävä kehitys.Nyt",
    "Kestävän muotoilun perusteet", "Digitaalinen visualisointi",
    "Muodin materiaalit ja tekniikat", "Lasin ja keramiikan materiaalit ja tekniikat",
    "Studiemiljö", "Muotoiluajattelun perusteet", "Företagsmiljö",
    "Muodin suunnittelu ja tekniikat", "Lasin ja keramiikan suunnittelu ja tekniikat",
    "Älykkään muotoilun perusteet", "Visuaalinen ja dokumentoiva portfolio",
    "Muodin mallintaminen ja tekniikat", "Lasin ja keramiikan mallintaminen ja tekniikat",
    "Viestinnän perusteet", "Color and Form", "Design Methods and Research",
    "Design Process Project", "English for Designers", "Smart and Sustainable Materials and Methods",
    "Futures Studies in Design", "Product Development Project", "Graphic Design"
  ],
  "Smart and Sustainable Design": [
    "Sketching and Visualization", "Digital Learning Environments", "Design in Culture",
    "Design Studio", "Basics of Sustainable Design", "Digital Visualization",
    "Materials and Techniques in Fashion", "Materials and Techniques in Glass and Ceramic",
    "Studiemiljo", "Finnish 1", "Basics of Design Thinking", "Design and Techniques in Fashion",
    "Design and Techniques in Glass and Ceramics", "Finnish 2", "Företagsmiljö",
    "Basics of Smart Design", "Visual and Documentary Portfolio", "Prototyping in Fashion",
    "Prototyping in Glass and Ceramics", "Viestimän perusteet", "Finnish 3", "Finnish 4",
    "Color and Form", "Design Methods and Research", "Design Process Project",
    "English for Designers", "Smart and Sustainable Materials and Methods",
    "Futures Studies in Design", "Product Development Project", "Graphic Design"
  ],
  "Tietojenkäsittelyn": [
    "Ohjelmoinnin perusteet", "Käyttöjärjestelmät", "Studiemiljö", "Tietokannat",
    "Olio-ohjelmointi", "Analysoinnin perusteet", "Tietovehot ja tietoturva",
    "Working English", "Staattisen verkkosivun rakentaminen", "Web-ohjelmointi",
    "Sisällönhallintajärjestelmät", "Företagsmiljö och arbetssökande",
    "Applied Application Project", "Software Development Tools", "Web Services",
    "Cloud Services", "Cloud-Based Business Solutions", "Agile Business Solution Development",
    "Tiedonkäsittely Pythonilla", "Ohjelmistotestaus", "Design Factory Project",
    "Viestintä asiakasprojekteissa", "Ennakoivat analytiikkamenetelmät Pythonilla",
    "Data-arkkitehtuuri ja -alystatyö", "Sosiaalisen ja digitaalisen median analytiikka",
    "Ohjelmistorobotiikka ja -automaatio", "Ohjelmiston suunnittelumenetelmät",
    "Miniprojekti", "Harjoittelu", "Web Accessibility", "JavaScript", "Web Framework Project",
    "Virtualization Techniques for Software Developers", "Cross-platform Development",
    "Mobile Programming Project"
  ],
  "Kestävän kehityksen": [
    "Ekologinen kestävyys - luonnon kantokyvyn rajat", "Projektinhallinta",
    "Kestävä kehitys.Nyt", "Kestävyyden ulottuvuudet", "Ruotsi 1", "Johdanto viestintään",
    "Tekniikka ympäristöalalla", "Professional English 1",
    "Luonnon monimuotoisuus - elämän edellytys", "Luonnon monimuotoisuus ja yhteiskunta",
    "Ruotsi 2", "Kiertotalous käytännössä", "Liikeideasta kiertotalousliiketoimintaan",
    "Innovaatio-osaaminen", "Ilmastonmuutos luonnontieteellisenä ja yhteiskunnallisena ilmiönä",
    "Hiilijalanjälki osana elinkaariarviointia", "DF Design Thinking",
    "Muotoiluajattelun projekti", "Professional English 2",
    "Kestävän yhteiskunnan toimijat ja ohjauskeinot", "Ympäristöterveys",
    "Vastuullinen viestintä", "Asiantuntijaviestintä"
  ],
  "Rakennetun ympäristön": [
    "Pihan suunnittelu", "Ammatillisen englannin perusteet",
    "Skaalautuvat rakennetun ympäristön prosessit", "Kestävä sosiaalinen ympäristö",
    "Kestävä kehitys.Nyt", "Rakenteet ja niiden mitoitus", "Ammatillinen englanti",
    "Kasvullinen ympäristö", "Yksityiset ja puolijulkiset ulkotilat",
    "Rakennetun ympäristön hallinnointimenetelmät", "Ruotsi", "Kunnossapito",
    "Työharjoittelu", "Asiantuntijaharjoittelu"
  ],
  "Maaseutuelinkeinojen": [
    "Agrologin toimintaympäristö tutuksi", "Kestävä kotieläintuotanto", "Ruotsi A",
    "Kestävä kasvituotanto", "Englanti", "Maatalouspolitiikka ja -tutkimus",
    "Kestävä kehitys.Nyt", "Ruotsi B", "Datatalous", "Viestintä",
    "Medialukutaldon työkalupakki", "Planning Rural Development",
    "Maatilan liiketoiminnan kehittäminen", "Harjoittelu maaseutuyrityksessä",
    "Valmentava harjoittelu", "Asiantuntijaharjoittelu"
  ],
  "Metsätalouden": [
    "Metsän biologia, lajisto ja kasvupaikat", "Metsätieto", "Metsien kestävän käytön ohjaus",
    "Kestävä kehitys.Nyt", "Johdanto viestintään", "Ammatillisen englannin perusteet",
    "Metsänhoidon menetelmät", "Ammatillinen englanti", "Metsien luonnonhoito",
    "Ilmastokestävä metsänhoito", "Puunhankinta 1", "Paikkatietoanalyysit",
    "Asiantuntijaviestintä", "Ammatillisen ruotsin perusteet", "Puunhankinta 2",
    "Ammatillinen ruotsi", "Metsäsuunnittelu ja arvon määritys",
    "Metsäverotus ja metsätilan sukupolven vaihdos", "Puun jalostus",
    "Metsäalan haasteet ja konfliktit"
  ],
  "Puutarhatalouden": [
    "Puutarhakasvit ja niiden kasvuympäristöt", "Ammattilisen englannin perusteet",
    "Kasvutekijöiden hallinta", "Kasvihuone- sekä kerrosviljely", "Ammattilinen englanti",
    "Viljely avomaalla sekä tunneleissa", "Kasvien käyttö pihoissa ja puutarhoissa",
    "Ruotsi", "Tuotannon suunnittelu ja kehittäminen", "Yrittäminen ja markkinointi"
  ],
  "Climate Smart Agriculture": [
    "Agricultural expertise", "Finnish 1", "Animal husbandry", "Swedish 1", "Finnish 2",
    "Crop plants and production", "Agricultural Research and Rural Policies", "Swedish 2",
    "Finnish 4", "English", "Finnish 3", "Research and farm practices during the growing season",
    "Preparatory training", "Analyzing data", "Communication", "Planning Rural Development",
    "Agricultural Diversity", "Agroecology", "Business and expert services in the field of agriculture",
    "Sustainable crop production", "Sustainable animal production",
    "Sustainable farm technology choices", "Further farm practices", "Further expert practice",
    "Sustainable Dairy Systems: Resource efficient and sustainable feed production",
    "Sustainable Dairy Systems: Animal husbandry and welfare", "Basics of Forest Nature",
    "Means of Control in Forestry", "Basics of Forest Management", "Wood Procurement Chain"
  ],
  "Sustainable Forest Management": [
    "Forest biology, species and habitats", "Finnish 1", "Forest information", "Finnish 2",
    "Guidance on Sustainable Forest Management", "Sustainable Development. Now",
    "Introduction to Communication", "Finnish 3", "Methods of Forest Management", "Finnish 4",
    "Climate-Resilient Forest Management", "Forest Nature Management", "Wood Procurement 1",
    "Spatial Data Analysis", "Professional Communication", "Basics of Professional English",
    "Wood Procurement 2", "Professional English", "Forest Property Management"
  ],
  "Professional Horticulture": [
    "Garden Plants and their Habitats", "Sustainable Development Now",
    "Basics of Professional English", "Growth Factors in Plant Production",
    "Controlled-environment Plant Production", "Professional English",
    "Horticulture on Open Fields and High Tunnels",
    "Selection and Use of Plants in Different Type of Gardens",
    "Planning and Development of Horticultural Production", "Entrepreneurship and Marketing",
    "Leadership and Supervisory Skills", "Skills of Seasonal Horticultural Work",
    "Finnish 1", "Finnish 2", "Finnish 3", "Finnish 4", "Sustainable Horticulture",
    "Improvement of Horticultural Cultivation Techniques", "Horticultural Crops Steering Systems",
    "Development and Innovations", "Research and Development in Horticulture"
  ],
  "Sosionomi": [
    "Yhteiskunnan rooli hyvän elämän edistäjänä", "Sosiaaliohjaus elämänkulun eri vaiheissa",
    "Opiskelijana ammattikorkeakoulussa", "Asiakastyön tietoperusta",
    "Asiakastyö ammatillisena vuorovaikutuksena", "Orientaatio sosiaalialan perustehtävään",
    "English for Social Services Studies", "Sosioiduturinen innostaminen kansalaisyhteiskunnassa",
    "Monikulttuurinen työ", "Viestintä- ja vuorovaikutustaidot",
    "Yhteiskehittäminen ja palvelumuotoilun menetelmät", "Asiakaslähtöinen palveluohjaus",
    "Palveluohjauksen simulaatiot", "Sosiaalihuollon asiakastieto, kirjaaminen ja tiedonhallinta",
    "Svenska för socialbranschen 1", "Tutkivan kehittämisen perusteet",
    "Tutkimus- ja kehittämistoiminnan käytännöt", "Svenska för socialbranschen 2",
    "Tutkimusviestintä", "Monialainen yhteistoiminta tiimeissä ja verkostoissa",
    "Johtaminen sosiaalialalla", "Lähijohtamisen harjoittelu", "English for workplace",
    "Työhyvinvointi ja työturvallisuus", "Yrittäjyys sosiaalialalla",
    "Ammatillisen kasvun portfolio", "English portfolio", "Viestinnän portfolio",
    "Kansainvälisyysosaaminen", "Ruotsin kirjallinen osaaminen", "Ruotsin suullinen osaaminen",
    "Lapsen kasvu ja kehitys", "Varhaiskasvatuksen pedagogisen toiminnan lähtökohdat",
    "Monipuoliset työtavat varhaiskasvatuksessa",
    "Lapsen kehityksen ja oppimisen tuki varhaiskasvatuksessa",
    "Varhaiskasvatuksen toimintakulttuuri ja sosiaalisen asiantuntijuus",
    "Taidelähtöiset menetelmät ja mediakasvatus", "Sosiaalityön teoria1ja käytännöt",
    "Elämänkulku ja sosiaalityö", "Taide, kulttuuri ja luonto sosiaalityössä",
    "Ennakoiva sosiaalityö", "Yhteisöt ja osallisuus voimavarana",
    "Sosiaalityö ja erityisen tuen tarpeet", "Lapsiperheiden sosiaalityö", "Avohuolto",
    "Sijaishuolto", "Nuoruus muuttuvassa yhteiskunnassa", "Nuorten syrjäytymisen ehkäisy",
    "Sosiokulttuurinen nuorisotyö", "Mielenterveys- ja päihdetyön lähtökohdat",
    "Osallisuutta ja asiakaslähtöisyyttä toteuttava mielenterveys- ja päihdetyö",
    "Kriisit elämänkulku", "Foundations of Cultural Well-Being",
    "Processes of Cultural Methods", "Developing Activity Models for Cultural Well-Being"
  ],
  "Sairaanhoitaja": [
    "Opiskelijana ammattikorkeakoulussa", "Viestinnän perusteet hoitotyössä",
    "Hoitotyön ruotsi 1", "Luonnontieteelliset opinnot", "Hoitotyön lähtökohdat",
    "Hoitotyön auttamismenetelmät", "Harjoittelu, hoitotyön perustaidot",
    "Mielenterveys- ja päihdehoitotyö 1", "Kirurgisen potilaan hoitotyö 1",
    "Sisätautipotilaan hoitotyö 1", "Hoitotyön ruotsi 2", "Mielenterveys- ja päihdehoitotyö 2",
    "Kirurgisen potilaan hoitotyö 2", "Sisätautipotilaan hoitotyö 2", "Hoitotyön englanti 1",
    "Terveyden edistäminen ja terveysteknologia", "Rokotusosaamisen perusteet",
    "Seksuaaliterveys, raskaus ja normaali synnytys", "Lasten ja nuorten hoitotyö",
    "Gerontologinen hoitotyö", "Projektiharjoittelu erilaisissa toimintaympäristöissä",
    "Yhteisöt ja monikulttuurillisuus viestinnässä", "Tutkimus- ja kehittämisosaaminen",
    "Johtajuusosaaminen", "Yrittäjyysosaaminen", "Kestävä kehitys.Nyt",
    "Ruotsin suullinen osaaminen", "Ruotsin kirjallinen osaaminen",
    "Sairaanhoitajan ydinosaamisen valtakunnallinen teoriakoe",
    "Sairaanhoitajan ydinosaaminen valtakunnallinen lääkelaskukoe",
    "Akuutti ja kiireetön avohoitotyö", "Akuutti mielenterveys- ja päihdehoitotyö",
    "Akuutti-, päivystys- ja tehohoitotyö", "Hoitotyön Englanti 2",
    "Intraoperatiivinen hoitotyö", "Lasten ja nuorten syventävä hoitotyö",
    "Palliatiivinen perhehoitotyö", "Syventävä lääkelaskenta",
    "Traumatisoituneen asiakkaan auttaminen", "Traumaattinen kriisi ja psykososiaalinen tuki",
    "Älykkaat hyvinvointipalvelut"
  ],
  "Terveydenhoitaja": [
    "Opiskelijana ammattikorkeakoulussa", "Viestinnän perusteet hoitotyössä",
    "Hoitotyön ruotsi 1", "Luonnontieteelliset opinnot", "Hoitotyön lähtökohdat",
    "Hoitotyön auttamismenetelmät", "Harjoittelu, hoitotyön perustaidot",
    "Mielenterveys- ja päihdehoitotyö 1", "Kirurgisen potilaan hoitotyö 1",
    "Sisätautipotilaan hoitotyö 1", "Hoitotyön ruotsi 2", "Mielenterveys- ja päihdehoitotyö 2",
    "Kirurgisen potilaan hoitotyö 2", "Sisätautipotilaan hoitotyö 2", "Hoitotyön englanti 1",
    "Terveyden edistäminen ja terveysteknologia", "Rokotusosaamisen perusteet",
    "Seksuaaliterveys, raskaus ja normaali synnytys", "Lasten ja nuorten hoitotyö",
    "Gerontologinen hoitotyö", "Projektiharjoittelu erilaisissa toimintaympäristöissä",
    "Yhteisöt ja monikulttuurillisuus viestinnässä", "Tutkimus- ja kehittämisosaaminen",
    "Johtajuusosaaminen", "Yrittäjyysosaaminen", "Kestävä kehitys.Nyt",
    "Ruotsin suullinen osaaminen", "Ruotsin kirjallinen osaaminen",
    "Sairaanhoitajan ydinosaamisen valtakunnallinen teoriakoe",
    "Sairaanhoitajan ydinosaamisen valtakunnallinen lääkelaskukoe",
    "Lapsiperheen terveydenhoitajatyö", "Rokotusosaamisen syventäminen",
    "Voimavaroja tukevat työmenetelmät", "Monialainen yhteistyö terveydenhoitajatyössä",
    "Koulu- ja nuoruuskäisen perheen terveydenhoitajatyö",
    "Yhteiskunnallinen terveydenhoitajatyö", "Työikäisen terveydenhoitajatyö",
    "Holtotyön Englanti 2", "Smart Welfare Services"
  ],
  "Health Care, Nursing": [
    "Finnish Language and Culture", "Studying at a Finnish University of Applied Sciences",
    "Basics of the Finnish Language", "Sustainable Development", "Natural Sciences I",
    "Finnish Language in Nursing", "Swedish in Nursing 1", "Natural Sciences II",
    "Nursing Basics", "Pharmacotherapy and Mathematical Skills I", "Nursing in Finnish",
    "Pharmacotherapy II", "Nursing Interventions",
    "Clients in the Health Care and Social Welfare Sector",
    "Health Care and Social Welfare Service Systems and Multi-Professional Work Professional Interaction I",
    "Medical Nursing", "Pharmacotherapy III",
    "Surgical, Perioperative, and Oncological Nursing", "Pharmacotherapy IV",
    "Gerontological Nursing", "Pharmacotherapy VI", "Palliative Nursing",
    "Sexual Health, Pregnancy, and Regular Delivery", "Paediatric Nursing",
    "Pharmacotherapy and Drug Calculations VI", "Promotion of Health and Health Technology",
    "Client Guidance in Finnish", "Research Communications", "Pharmacotherapy VIII",
    "Nursing in Acute, Emergency, and Intensive Care",
    "Nursing in Acute and Non-Urgent Non-Institutional Care",
    "Nursing in Palliative Family Care", "Acute Mental Health and Substance Abuse Nursing",
    "Intra-Operational Nursing", "Advanced Paediatric Nursing"
  ],
  "Rakennus- ja yhdyskuntatekniikan, Insinööri (Rakennustekniikka)": [
    "Rakentamisen perusteet", "Geometria ja lineaarialgebra", "Johdanto tekniikan fysiikkaan",
    "Rakennusmateriaalit", "Geotekniikka", "Kemia", "Algebra", "Puurakentaminen 1",
    "CAD-perusteet", "Rakennussuunnittelun ja tietomallinnuksen perusteet",
    "Rakennusfysiikka 1", "Statiikka 1", "Differentiaallaskenta", "Tekniikan viestintä 1",
    "Pientalon kustannuslaskenta", "Rakennesuunnittelun perusteet", "Työmenetelmät",
    "Rakenteiden mitoitus", "Statiikka 2", "Integraalilaskenta",
    "Yhdyskuntarakentamisen perusteet", "Betonirakentamisen perusteet", "Mittaustekniikka 1",
    "Pohjarakennustekniikka", "Lujiusoppi 1", "Tekniikan englanti 1",
    "Rakentamistalouden perusteet", "Betoniteknologia", "Betonirakenteiden suunnittelu 1",
    "Lujiusoppi 2", "Tekniikan englanti 2", "Betonirakenteiden suunnittelu 2",
    "Talotekniikka", "Materiaalien kestävyys", "Rakennustyömaan turvallisuus",
    "Kerrostalon rakenteet", "Rakenneanalyysi", "Tekniikan ruotsi 1", "Työnjohtaminen",
    "Tietomalli tuotannossa suunnittelussa", "Tekniikan ruotsi 2", "Aikatauluhallinta",
    "Laatujohtaminen", "Betonirakentaminen", "Betonirakenteiden suunnittelu 3",
    "Tietomallintaminen 1", "Rakennustysliikka 2", "Korjausrakentaminen 1",
    "Korjausrakentamisen rakennustysliikka", "Työmaahallinta", "Kustannushallinta",
    "Teräsrakentaminen", "Mittaustekniikka 2", "Rakenteiden mekaniikka",
    "Teräsrakenteiden suunnittelu 1", "Korjausrakentaminen 2",
    "Rakenteet korjausrakentamisessa", "Tietomallintaminen 2", "Yleiset sopimusehdot",
    "Rakentamisen ilmastovaikutukset", "Korjausrakentamisen rakennesuunnittelu",
    "Teräsrakenteiden suunnittelu 2"
  ],
  "Rakennus- ja yhdyskuntatekniikan, Insinööri (Rakennustuotanto)": [
    "Rakentamisen perusteet", "Kestävä kehitys.Nyt", "Johdanto tekniikan fysiikkaan",
    "Geometria ja lineaarialgebra", "Rakennusmateriaalit", "Puurakentaminen 1",
    "Geotekniikka", "CAD-perusteet", "Kemia", "Algebra", "Pientalohankkeen valvonta",
    "Rakennussuunnittelun ja tietomaliinnuksen perusteet", "Rakennusfysiikka 1",
    "Statiikka 1", "Tekniikan viestintä 1", "Pientalon kustannuslaskenta",
    "Rakennesuunnittelun perusteet", "Rakenteiden mitoitus", "Betonirakentamisen perusteet",
    "Työmenetelmät", "Statiikka 2", "Yhdyskuntarakentamisen perusteet", "Maarakentaminen",
    "Rakennustyömaan turvallisuus", "Mittaustekniikka 1", "Lujuusoppi 1",
    "Tekniikan englanti 1", "Lujuusopin perusteet", "Rakentamistalouden perusteet",
    "Puurakentaminen 2", "Betontieknologia", "Rakentamisen ilmastovaikutukset",
    "Tekniikan englanti 2", "Kerrostalon rakenteet", "Kerrostalotyömaan hallinta",
    "Betontiyön johtaminen", "Tehtäväsuunnittelun perusteet", "Talotekniikka",
    "Tekniikan ruotsi 1", "Hankintojen ohjaus", "Työnjohtaminen", "Aikatauluhallinta",
    "Tietomalli tuotannossa", "Tekniikan ruotsi 2", "Työmaa- ja tuotantotekniikka",
    "Esihenkilötoiminta", "Materiaalien kestävyys", "Teräsrakentaminen",
    "Kustannushallinta", "Korjausrakentaminen ja linjasaneeraus",
    "Korjausrakentamisen rakennusfysiikka", "Purkusuunnittelu", "Yleiset sopimusehdot",
    "Tekniikan viestintä 2"
  ],
  "Sähkö- ja automaatiotekniikan": [
    "Geometria ja lineaariaigebra", "Automaatiotekniikan perusteet", "Tekniikan viestintä 1",
    "Kestävä kehitys.Nyt", "Algebra", "Tekniikan englanti 1", "Sähkömittaustekniikka",
    "Sähkö- ja automaatiotekniikan laboratorioharjoitukset", "Differentiaalilaskenta",
    "Tekniikan ruotsi 1", "Teoreettinen sähkötekniikka - DC", "Sähkönjakeluverkot",
    "Ohjelmoinnin perusteet", "Integraalilaskenta", "Tekniikan ruotsi 2",
    "Mittausjärjestelmät", "Mekaniikka", "3D-mallinnus",
    "Logiikkaohjelmointi ja käyttöliittymät", "Tietoverkot ja tietoturva",
    "Virtaus, lämpöoppi ja termodynamiikka",
    "Rakennusten sähköverkkojen asennukset ja asennustakastukset",
    "Rakennusten sähköverkkojen suunnittelu", "Sähkö, magnetismi ja aaltoliike",
    "Sähköturvallisuussäädökset ja standardit", "Teoreettinen sähkötekniikka - AC",
    "Kiinteistön energiajärjestelmät", "Rakennusten sähkökäytöt",
    "Rakennusten sähköverkkojen automaatio", "Sähkön pientuotanto ja varastointi",
    "Tekniikan viestintä 2", "Työskentely kansainvälisessä projektissa",
    "IoT-järjestelmät", "Differentiialalyhtälöt ja todennäköisyyslaskenta",
    "Processimittaukset", "Tekniikan englanti 2", "Keinoäly", "Robotiikka",
    "Mallinnus ja simulointi", "Sähkö- ja kenttäsuunnittelu", "Teollisuuden kenttäväylät",
    "Sääötekniikka", "Automaatiosuunnittelu", "Koneturvallisuus", "Virtuaalinen käyttöönotto",
    "Konenäkö", "Tuotantoprosessin sähkösuunnittelu", "Kunnossapidon perusteet",
    "Kunnossapidon suunnittelu", "Kunnossapidon tietojärjestelmät",
    "Sähköverkon simulointi", "Sähköalan yrittäjyys", "Sähkönjakeluverkkojen matematiikka",
    "Sähkötyöturvallisuus", "Suurjännitetekniikka", "Liikkeenohjaus automaatiossa",
    "Tuotannon simulointi", "Modernit käyttöliittymät teollisuudessa", "Home Automation",
    "Surveillance and Safety", "Domestic Robotics"
  ],
  "Bio- ja elintarviketekniikan": [
    "Geometria ja lineaariaigebra", "Automaatiotekniikan perusteet", "Tekniikan viestintä 1",
    "Ammattialaan tutustuminen", "Kemian ja mekaniikan perusteet",
    "Geometria ja lineaarialgebra", "Johdanto viestintään", "Mittaukset ja tulosten käsittely",
    "Projektinhallinta", "Algebra", "Kestävä kehitys.Nyt",
    "Tuotantoprosessin toiminta, hygienia ja turvallisuus", "Differentiaalilaskenta",
    "Professional English 1", "Organinen kemia ja mikrobiologia", "Integraalilaskenta",
    "Professional English 2", "Toimiva tuotantoprosessi", "Laadunhallinta",
    "DF Design Thinking", "Muotoiluajattelun projekti", "Ruotsi 1",
    "Yksikköprosessit ja biokemia", "Asiantuntijaviestintä", "Ruotsi 2",
    "Teollinen biotekniikka ja uudet tuotantoprosessit", "Ruotsin suullinen osaaminen",
    "Ruotsin kirjallinen osaaminen", "Elintarviketeknologia", "Biomassan jalostus",
    "Meijerin perusprosessit", "Nestemäiset ja hapatetut meijerituotteet",
    "Juustot ja juustonkaltaiset tuotteet", "Meijeriteknologioiden erityisosaaminen",
    "Kulvatut tuotteet ja heravalmisteet", "Ravintorasvat, jäätelöt ja välipalatuotteet"
  ],
  "Liikennealan": [
    "Digitalinen työskentely", "Opiskelijana HAMKissa", "Liikenteen toimintakenttä ja lähtökohdat",
    "Algebra", "Tekniikan viestintä 1", "Liikenneturvallisuus", "Esteettömyys",
    "Yhdyskuntasuunnittelun perusteet", "Tekniikan englanti 1",
    "Liikennepolitiikka ja kuljetukset", "Liikenteen ympäristövaikutukset",
    "Paikkatietoaineistot ja kartat", "Tekniikan ruotsi 1", "Liikennesuunnittelun perusteet",
    "Liikennemittaukset", "Geometria", "Tekniikan ruotsi 2", "Viisas liikkuminen",
    "Liikkumissuunnitelman tekeminen", "Liikennettukimukset ja niiden analysointi",
    "Tekniikan englanti 2", "The-ja katusuunnittelu", "CAD-sovellukset",
    "Mekaniikan perusteet", "Liikennejärjestelmäsuunnittelu",
    "Liikennetalous ja vaikutusten arviointi", "Joukkoliikenteen suunnittelu",
    "Älykäs liikenne", "Autonomiset ajoneuvot", "Liikenteen informaatio ja palvelut",
    "Tekniikan viestintä 2"
  ],
  "Information and Communication Technology, Circular Economy": [
    "Basics of Programming", "Geometria ja lineaarialgebra", "Introduction to Communication",
    "Finnish 1", "Microcontrollers", "Introduction to Information Networks",
    "Digital Services", "Algebra", "Technical English 1", "Finnish 2", "Databases",
    "Python for Data Science", "Circular Economy Value Chains", "Technical English 2",
    "Finnish 3", "DF Data Analysis Project", "DF Data-based Decision Making",
    "DF Data Analytics Tools", "DF Quantitative Reasoning for Data Analytics", "Finnish 4",
    "Circular Economy Principles", "Innovation Methods", "DF Design Thinking",
    "Project Management", "DF Circular Business Design", "Basics of IoT", "IoT Project",
    "Basics of 3D Modelling and 3D Printing", "Systems and Sensors",
    "Electricity and Magnetism", "Differentialflaskenta", "Sensor Systems Project",
    "Professional Communication", "Principles of Cloud Services", "Cloud Services Project",
    "User Interface Design and Usability", "Applied Physics", "Integraallaskenta",
    "3D Modelling and Printing", "Team Work Management and Finance",
    "Value Driven Procurement", "Lean as the Cornerstone of Efficiency",
    "Management and Responsible Procurement Project", "Cross-Cultural Communication",
    "Sustainable Society and Global Economy", "Creating Sustainable Solutions",
    "Development Project", "Mathematics for Data Science with Python",
    "Applied Machine Learning", "Big Data Analytics", "Neural Networks for Computer Vision",
    "AI Search Algorithms", "Development of AI Applications", "Cybersecurity",
    "Cyber Attacks and Defense Methods", "Penetration Tests, Audits and Red Teaming"
  ],
  "Tieto- ja viestintätekniikka, Kiertotalouden": [
    "Ohjelmoinnin perusteet", "Algebra", "Projektinhallinta", "Tekniikan viestintä 1",
    "Mikrokontrollerit", "Tietoverkkojen perusteet", "Digitaaliset palvelut",
    "Geometria ja lineaarialgebra", "Tekniikan englanti 1", "Tietokantojen perusteet",
    "Python for Data Science", "Arvoketjut kiertotaloudessa", "Medialukuraito",
    "Tekniikan englanti 2", "DF Data-analytiikan projektityö", "DF Tiedolla johtaminen",
    "DF Data-analytiikan työkalut", "DF Tilastollinen ajattelu data-analytiikassa",
    "Tekniikan ruotsi 1", "Kiertotalouden periaatteet", "Innovaatio-osaaminen",
    "DF Design Thinking", "DF Circular Business Design", "Teknikan ruotsi 2",
    "IoT-perusteet", "IoT-projekti", "3D-mallinnuksen ja -tulostuksen perusteet",
    "Järjestelmät ja anturit", "Sähköoppi ja magnetismi", "Differentiaalilaskenta",
    "Anturijärjestelmä-projekti", "Teknikan viestintä 2", "Pihipalveluiden perusteet",
    "Pihipalvelut-projekti", "User Interface Design and Usability", "Soveltava fysiikka",
    "Integraalilaskenta", "Tihnityön johtaminen ja talous", "Arvo-ohjatut hankinnat",
    "Lean tehokkuuden kulmakivenä", "Johtaminen ja hankinnat -projekti",
    "Cross-Cultural Communication", "Sustainable Society and Global Economy",
    "Creating Sustainable Solutions", "Neural Networks for Computer Vision",
    "AI Search Algorithms", "Development of AI Applications", "Cybersecurity",
    "Cyber Attacks and Defense Methods", "Penetration Tests, Audits and Red Teaming",
    "Mathematics for Data Science with Python", "Applied Machine Learning", "Big Data Analytics"
  ],
  "International Business": [
    "Business Mathematics", "Study Essentials", "Digital and Technological Skills",
    "Global Business Environment", "English in a Global Context", "Introduction to Research",
    "Foundations of Economics", "Legal Environment", "Marketing Essentials",
    "Study Environment in Swedish", "Finnish 1", "Principles of Accounting",
    "Organizational Communication", "Business Environment in Swedish", "Finnish 2",
    "Management Essentials", "Principles of Sustainability", "Project Management",
    "Sales and Customer Service", "Sustainability Project and Communication",
    "Introduction to Business Information Management", "Finnish 3", "Finnish 4",
    "Finding Business Opportunities through Innovation", "Business Planning Process",
    "Legal Environment of an Entrepreneur", "Pitching Skills", "Circular Economy",
    "Organizational Behaviour", "Supply Chain Management", "Cross Cultural Communication",
    "Management Accounting", "Customer Relationship Management", "Positioning and Branding",
    "Digital Marketing Expression", "Marketing with Data", "Developing Professional Profile",
    "Business Ethics", "Practical Implementation of Analytics", "Specialization Unit",
    "Content Laboratory", "Building Networks for career development", "European Markets",
    "Brussels Project", "Business Analytics", "Business Intelligence",
    "Financial Business Analysis", "Corporate Social Responsibility", "Marketing Trends",
    "Applying Diversity Marketing", "Marketing for Sustainability",
    "Human Resource Development", "Change Management",
    "Concepts and Models of Strategy Process"
  ],
  "Liiketalouden": [
    "Business Mathematics", "Study Essentials", "Digital and Technological Skills",
    "Digistartti ja orientaatio", "HAMKDIIit: Liiketoiminta ja Markkinointi",
    "Yritysjuridiikka", "Taloustieteen perusteet", "Working Life English",
    "Liikeideasta liiketoimintaan", "Johdon laskentatoimi", "Studiemiljö",
    "Kirjanpidon perusteet ja käytäntö", "Digitaalinen markkinointi",
    "Viestintä ja työyhteisötaidot", "Company World", "Henkilökohtaisen osaamisen kehittyminen",
    "Käytännön kirjanpito ja tilinpäätös", "Liiketoiminnan strategiat ja kokeilut",
    "Markkinoinnin suunnittelu", "Företagsmiljö", "Ammatilliset valinnat",
    "Kustannuslaskenta, hinnoittelu ja budjetointi", "Asiakkuudet ja myynti",
    "Liiketalousviestintä", "Henkilöstöjohtamisen perusteet",
    "Henkilöstöjohtaminen käytännössä", "Työlainsäädäntö",
    "Opinnäytetyö HAMK liiketaloudessa", "Liiketalouden kehittämis- ja tutkimusmenetelmät",
    "Omavalintainen opintojakso",
    "Eri yritysmuotojen kirjanpidon ja tilinpäätöksen erityiskysymykset",
    "Arvonlisäverotuksen erityiskysymykset", "Digitaalinen taloushallinto",
    "Henkilöverotus", "Yritysverotus ja tilinpäätössuunnittelu",
    "Tilintarkastuksen perusteet", "Junior KLT-tentti",
    "Sisäinen valvonta ja kestävyysraportointi", "Yritysanalyysi",
    "Talousohjaus liiketoiminnan tukena", "Tilinpäätösanalyysi",
    "Kestävä ja kehittyvä markkinointi", "Visuaalisuus ja tekstit markkinoinnissa",
    "Markkinoinnin kehittämisprojekti", "Business Design", "Service Design",
    "Business Design projekti", "Tapahtumamuotoilu", "Tapahtumatuotannon projekti",
    "Marketing Trends", "Applying Diversity Marketing", "Marketing for Sustainability",
    "Sijoittaminen ja varainhoito", "Riskienhallinta ja vakuuttaminen",
    "Investointipäätöksenteko ja sitä tukeva laskenta", "Business Analytics",
    "Business Intelligence", "Financial Business Analysis", "Palkanlaskenta",
    "Palkanlaskennan erityiskysymykset", "Palkkahallinnon projekti", "Asiantuntijabrändi",
    "Kauppa- ja varallisuusoikeuden perusteet", "Fasilitointi",
    "Henkilöstöjohtamisen projekti", "Urheilun liiketoimintamallit",
    "Urheilumarkkinointi ja brändi", "Urheiluliiketoiminnan projekti"
  ],
  "Hevosalan liiketoiminnan": [
    "Digistartti ja orientaatio", "HAMKDIIit: Liiketoiminta ja Markkinointi",
    "Yritysjuridiikka", "Working Life English", "Taloustieteen perusteet",
    "Liikeideasta liiketoimintaan", "Johdon laskentatoimi", "Studiemiljö",
    "Kestävä kehitys.Nyt", "Kirjanpidon perusteet ja käytäntö", "Digitalinen markkinointi",
    "Viestintä ja työyhteisötaidot", "Company World", "Henkilökohtaisen osaamisen kehittyminen",
    "Käytännön kirjanpito ja tilinpäätös", "Liiketoiminnan strategiat ja kokeilut",
    "Markkinoinnin suunnittelu", "Företagsmiljö", "Ammatilliset valinnat",
    "Kustannuslaskenta, hinnoittelu ja budjetointi", "Asiakkuudet ja myynti",
    "Liiketalousviestintä", "Henkilöstöjohtamisen perusteet",
    "Henkilöstöjohtaminen käytännössä", "Työlainsäädäntö",
    "Opinnäytetyö HAMK liiketaloudessa", "Liiketalouden kehittämis- ja tutkimusmenetelmät",
    "Omavalintainen opintojakso", "Tapahtumamuotoilu", "Tapahtumatuotannon projekti",
    "Kestävä ja kehittyvä markkinointi", "Visuaalisuus ja tekstit markkinoinnissa",
    "Markkinoinnin kehittämisprojekti", "Business Design", "Service Design",
    "Business Design projektii", "Urheilun liiketoimintamallit",
    "Urheilumarkkinointi ja brändi", "Startup Business School", "Kevytyrittäjyys",
    "Kaupallistamisen perusteet", "Immateriaalioikeuksien perusteet",
    "Yrityksen perustaminen", "Asiantuntijärjändi",
    "Kauppa- ja varallisuusoikeuden perusteet", "Fasilitointi",
    "Henkilöstöjohtamisen projekti", "Tallivmpäristö ja kestävä hevosengito",
    "Hevosen hyvinvointi ja käyttäytyminen", "Hevosjalostus",
    "Hevosen ravinnontarve ja ruokinta"
  ]
};

async function seedSubjects() {
  const pool = mysql.createPool({
    host: '127.0.0.1',
    user: 'root',
    password: 'Uniclips_26',
    database: 'uniclips',
    port: 3306
  });

  try {
    console.log('🗑️  Clearing existing subjects...');
    await pool.query('DELETE FROM subjects');
    
    console.log('📝 Inserting new subjects...');
    let totalInserted = 0;
    
    for (const [program, subjects] of Object.entries(degreePrograms)) {
      for (const subject of subjects) {
        await pool.query(
          'INSERT INTO subjects (name, degree_programmes) VALUES (?, ?)',
          [subject, program]
        );
        totalInserted++;
      }
      console.log(`✅ ${program}: ${subjects.length} subjects inserted`);
    }
    
    console.log(`\n🎉 Done! Total subjects inserted: ${totalInserted}`);
    console.log(`📚 Total degree programs: ${Object.keys(degreePrograms).length}`);
    
  } catch (error) {
    console.error('❌ Error:', error.message);
  } finally {
    await pool.end();
  }
}

seedSubjects();
